educates:
  trainingPortals:
    -
      portalDomain:
      robotUser:
      robotPassword:
      robotClientId:
      robotSecret:
      indexUrl:
    -
      portalDomain:
      robotUser:
      robotPassword:
      robotClientId:
      robotSecret:
      indexUrl:
